### ISSUE TITLE
对于基于 OlivOS/userModule 扩展而来的 API，把文档写在哪里呢

### ISSUE THREAD

**Issue by raininboat** [OlivOS-Team/OlivOSDoc#7]
RT，想起来我之前 userModule 里面写了一个内置的插件的简单配置数据库API，但一直没有写文档
如果我要给他编写文档，请问可以写在哪里呢？
注，目前它是依托于 `插件托盘` 运行的，如果我直接写在插件API会不会使得其变得更加混乱，是否应该链接至新开的一个页面中，专门提供给所有 userModule 编写文档？
相关代码行：
https://github.com/OlivOS-Team/OlivOS/blob/458363b3eb60f350d7bf83f0aaf5eb9e8869641f/OlivOS/core/core/pluginAPI.py#L133

**Comment by lunzhiPenxil** [comment]
是的，你应当链接至一个新开的页面，事实上，我推荐你分别编写两个文档，一个是这个模块的功能实现与维护文档，这个页面可以与位于   
https://github.com/OlivOS-Team/OlivOSDoc/tree/main/docs/DevGuild   
这个目录下，因为它是`OlivOS`的内部机制，这部分只需要`OlivOS`的维护者进行浏览，这里可以描述这个模块的实现方法与细节

另一个，你可以编写一个插件开发者在插件中调用这个模块的功能的指南与代码范例，它可以位于
https://github.com/OlivOS-Team/OlivOSDoc/tree/main/docs/DevPlugin
这个目录下，因为它是暴露给插件开发者的接口与功能

**Comment by lunzhiPenxil** [comment]
> 是的，你应当链接至一个新开的页面，事实上，我推荐你分别编写两个文档，一个是这个模块的功能实现与维护文档，这个页面可以与位于 https://github.com/OlivOS-Team/OlivOSDoc/tree/main/docs/DevGuild 这个目录下，因为它是`OlivOS`的内部机制，这部分只需要`OlivOS`的维护者进行浏览，这里可以描述这个模块的实现方法与细节
> 
> 另一个，你可以编写一个插件开发者在插件中调用这个模块的功能的指南与代码范例，它可以位于 https://github.com/OlivOS-Team/OlivOSDoc/tree/main/docs/DevPlugin 这个目录下，因为它是暴露给插件开发者的接口与功能

我建议先完成后者
